export default [{
        id: 1,
        header: 'The 2021 Design & Content Conference',
        authorLang: 'PERSONAL',
        authorList1: 'Full Stack Dev',
        authorList2: '2021',
        imgSrc: './images/capston.png',
        para: `Designers and content strategists team up.
        Hear from industry leaders about crafting experiences and telling stories that shape the future of the web.
        Two days of talks and thoughtful extras focused on delivering inclusive content and design outcomes.`,
        langList1: 'html',
        langList2: 'css',
        langList3: 'javascript',
        link1: 'https://mohamedelshamy55.github.io/firstcapstone/',
        link2: 'https://github.com/mohamedelshamy55/firstcapstone',
    },
    {
        id: 2,
        header: 'To Do List project',
        authorLang: 'PERSONAL',
        authorList1: 'Full Stack Dev',
        authorList2: '2021',
        imgSrc: './images/todolist.png',
        para: `To Do List project is list of todo items,
        users can add and remove item from todo list.`,
        langList1: 'html',
        langList2: 'css',
        langList3: 'javascript',
        link1: 'https://mohamedelshamy55.github.io/To-Do-List/',
        link2: 'https://github.com/mohamedelshamy55/To-Do-List',
    },
    {
        id: 3,
        header: 'awsame-book',
        authorLang: 'PERSONAL',
        authorList1: 'Full Stack Dev',
        authorList2: '2021',
        imgSrc: './images/awsamebookscreenshot.png',
        para: ` "Awesome books" is a simple website that displays a list of books and allows you to add and remove books from that list.
        By building this application, you will learn how to manage data using JavaScript.`,
        langList1: 'html',
        langList2: 'css',
        langList3: 'javascript',
        link1: 'https://mohamedelshamy55.github.io/Awesome-Books/',
        link2: 'https://github.com/mohamedelshamy55/Awesome-Books',
    },
    {
        id: 4,
        header: 'Portfolio-bootstrap',
        authorLang: 'PERSONAL',
        authorList1: 'Full Stack Dev',
        authorList2: '2021',
        imgSrc: './images/bootstrap1.png',
        para: ` Portfolio-bootstrap is a simple site designed by using bootstrap.`,
        langList1: 'html',
        langList2: 'css',
        langList3: 'javascript',
        link1: 'https://mohamedelshamy55.github.io/Portfolio-Bootstrap/',
        link2: 'https://github.com/mohamedelshamy55/Portfolio-Bootstrap',
    },
];