export default [{
        id: 1,
        header: 'The 2021 Design & Content Conference',
        authorLang: 'PERSONAL',
        authorList1: 'Front End Dev',
        authorList2: '2021',
        imgSrc: './images/capston.png',
        para: `Designers and content strategists team up. Hear from industry leaders about crafting experiences and telling stories that shape the future of the web. Two days of talks and thoughtful extras focused on delivering inclusive content and design outcomes.`,
        langList1: 'html',
        langList2: 'css',
        langList3: 'javascript',
        link1: 'https://mohamedelshamy55.github.io/firstcapstone/',
        link2: 'https://github.com/mohamedelshamy55/firstcapstone',
    },
    {
        id: 2,
        header: 'To Do List project',
        authorLang: 'PERSONAL',
        authorList1: 'Front End Dev',
        authorList2: '2021',
        imgSrc: './images/todolist.png',
        para: `To Do List project is list of todo items, users can add and remove item from todo list.`,
        langList1: 'html',
        langList2: 'css',
        langList3: 'javascript',
        link1: 'https://mohamedelshamy55.github.io/To-Do-List/',
        link2: 'https://github.com/mohamedelshamy55/To-Do-List',
    },
    {
        id: 3,
        header: 'Facebook 360',
        authorLang: 'FACEBOOK',
        authorList1: 'Full Stack Dev',
        authorList2: '2015',
        imgSrc: './images/third_large.png',
        para: ` Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quibusdam,
    explicabo. Dolorum eum vitae, quae voluptatem earum debitis minus, facere,
    at tenetur excepturi nihil! Commodi tenetur cumque iure quos nesciunt sunt!`,
        langList1: 'html',
        langList2: 'ruby on rails',
        langList3: 'css',
        langList4: 'javascript',
    },
    {
        id: 4,
        header: 'Uber Navigation',
        authorLang: 'Uber',
        authorList1: 'Lead Developer',
        authorList2: '2018',
        imgSrc: './images/fourth_large.png',
        para: ` Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quibusdam,
    explicabo. Dolorum eum vitae, quae voluptatem earum debitis minus, facere,
    at tenetur excepturi nihil! Commodi tenetur cumque iure quos nesciunt sunt!`,
        langList1: 'html',
        langList2: 'ruby on rails',
        langList3: 'css',
        langList4: 'javascript',
    },
];